Repository MHRA/products, pull requests merged in 2019-12, with the labels that each got.

#32 Update search indexes & move to MHRA Azure.
  medicines/search/definitions/indexers/azureblob-indexer.json
  medicines/search/definitions/indexes/azureblob-index.json
  medicines/web/.env
  medicines/web/components/mip/azure-search.ts
Labels: enhancement 💫

#36 Search routing (back button)
  medicines/web/components/mip/index.tsx
  medicines/web/components/search-results/index.tsx
  medicines/web/package.json
  medicines/web/yarn.lock
Labels: enhancement 💫, website 💻

#37 Change clickable area of search results
  medicines/web/components/mip/index.tsx
  medicines/web/components/search-results/index.tsx
Labels: enhancement 💫, r4r :eyes:, website 💻

#44 Modify format for Created dates in search results
  medicines/web/components/mip/index.tsx
  medicines/web/components/search-results/index.tsx
Labels: enhancement 💫, good first issue, r4r :eyes:, website 💻

#46 Escape AND, OR, and NOT in search (these are being treated as operands).
  medicines/web/components/mip/azure-search.ts
Labels: bug, r4r :eyes:, website 💻

#47 Pagination navigation
  medicines/web/components/mip/azure-search.ts
  medicines/web/components/mip/index.tsx
  medicines/web/components/search-results/index.tsx
  medicines/web/components/search-results/pagination.tsx
Labels: enhancement 💫, r4r :eyes:, website 💻

#55 Fix submit url
  medicines/web/components/mip/index.tsx
Labels: bug

#54 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, r4r :eyes:

#59 Add Readme to Search & Import tools.
  medicines/import/README.md
  medicines/search/README.md
Labels: documentation, enhancement 💫, r4r :eyes:

#66 Small ui fixes
  medicines/web/components/mip/index.tsx
Labels: bug, enhancement 💫, website 💻

#53 Active Substance navigation
  medicines/web/components/drug-index/index.tsx
  medicines/web/components/footer/index.tsx
  medicines/web/components/mip/index.tsx
  medicines/web/components/page/index.tsx
  medicines/web/model/substance.ts
  medicines/web/package.json
  medicines/web/services/azure-search.ts
  medicines/web/services/substance-loader.ts
  medicines/web/styles/colors.ts
  medicines/web/yarn.lock
Labels: r4r :eyes:

#65 Fix security alert from serialize-javascript (update to 2.1.2)
  medicines/web/yarn.lock
Labels: bug, website 💻

#60 Pagination styling
  medicines/web/components/search-results/pagination-groups.ts
  medicines/web/components/search-results/pagination.tsx
  medicines/web/styles/colors.ts
Labels: great gif :clap:, r4r :eyes:

#69 Render a cookie policy
  medicines/web/components/cookie-policy/index.tsx
  medicines/web/components/page/index.tsx
  medicines/web/styles/colors.ts
Labels: enhancement 💫, r4r :eyes:, website 💻

#71 Accessibility page
  medicines/web/next.config.js
  medicines/web/package.json
  medicines/web/pages/accessibility.md
  medicines/web/pages/accessibility.tsx
  medicines/web/yarn.lock
Labels: website 💻

#79 trim search term
  medicines/web/components/mip/index.tsx
Labels: bug, r4r :eyes:

#80 URL Structure
  medicines/web/components/drug-index/index.tsx
Labels: enhancement 💫, r4r :eyes:, website 💻

#85 Firefox styling for inputs
  medicines/web/components/search/index.tsx
Labels: bug, r4r :eyes:

#89 Putting the yellowcard back in the main layout for mobile
  medicines/web/components/mip/index.tsx
Labels: bug, r4r :eyes:

#88 Moving About copy into copy/about.md
  medicines/web/copy/about.md
  medicines/web/pages/about.tsx
Labels: r4r :eyes:

#90 Footer policies
  medicines/web/components/footer/index.tsx
  medicines/web/pages/privacy.tsx
Labels: r4r :eyes:

#92 Correcting small typo
  medicines/web/copy/homepage.md
Labels: website 💻

#98 #73 Trailing slash pages so /about/index.html is created
  medicines/web/next.config.js
Labels: bug, r4r :eyes:

#42 Add Google Analytics with hard-coded tracking ID.
  medicines/web/.env
  medicines/web/components/mip/index.tsx
  medicines/web/components/pdf/index.tsx
  medicines/web/components/search-results/index.tsx
  medicines/web/next.config.js
  medicines/web/package.json
  medicines/web/pages/_app.tsx
  medicines/web/pages/_document.tsx
  medicines/web/yarn.lock
Labels: enhancement 💫, great gif :clap:, r4r :eyes:, website 💻

#95 Disclaimer
  medicines/web/components/disclaimer/index.tsx
  medicines/web/components/search-results/index.tsx
  medicines/web/hooks/index.tsx
Labels: enhancement 💫, r4r :eyes:, website 💻

#102 Update homepage.md
  medicines/web/copy/homepage.md
Labels: r4r :eyes:

#112 Further improvements to the import script
  medicines/Cargo.lock
  medicines/import/Cargo.toml
  medicines/import/README.md
  medicines/import/src/cli.yaml
  medicines/import/src/main.rs
  medicines/import/src/metadata.rs
  medicines/import/src/par.rs
  medicines/import/src/spc_pil.rs
  medicines/import/src/storage.rs
Labels: cli tools :hammer_and_wrench:, enhancement 💫

#122 Sitemap
  medicines/web/package.json
  medicines/web/tools/sitemap-generator.js
Labels: cli tools :hammer_and_wrench:, enhancement 💫, r4r :eyes:, website 💻

#128 Cookie policy copy
  medicines/web/copy/cookies.md
  medicines/web/pages/cookies.tsx
Labels: enhancement 💫, r4r :eyes:, website 💻

#130 #111 Footer links are absolute
  medicines/web/components/footer/index.tsx
Labels: bug, website 💻

#129 Remove hard-coding names in search tool & hard-coded .env from JS sources
  azure-pipelines.yml
  medicines/Cargo.lock
  medicines/search/Cargo.toml
  medicines/search/README.md
  medicines/search/definitions/datasources/default.json
  medicines/search/definitions/indexers/default.json
  medicines/search/definitions/indexes/default.json
  medicines/search/src/azure_rest.rs
  medicines/search/src/cli.yaml
  medicines/search/src/datasource.rs
  medicines/search/src/env.rs
  medicines/search/src/index.rs
  medicines/search/src/indexer.rs
  medicines/search/src/lib.rs
  medicines/search/src/main.rs
  medicines/web/.env
  medicines/web/README.md
Labels: cli tools :hammer_and_wrench:, enhancement 💫, high priority, r4r :eyes:, website 💻

#131 Accessibility colour changes
  medicines/web/components/cookie-policy/index.tsx
  medicines/web/components/page/index.tsx
  medicines/web/components/search-results/index.tsx
  medicines/web/components/yellow-card/index.tsx
Labels: a11y :wheelchair:, r4r :eyes:, website 💻

#126 Fix learning branch build root path
  azure-pipelines.yml
  learning/web/gatsby-config.js
  learning/web/package.json
  learning/web/src/components/Sidebar/index.js
Labels: bug, learning modules 🎓, r4r :eyes:

#124 Tweaks to antipsychotic learning content
  learning/web/content/modules/antipsychotics/CON155606_12.mdx
  learning/web/content/modules/antipsychotics/CON155606_26.mdx
  learning/web/content/modules/antipsychotics/CON155606_3.mdx
  learning/web/content/modules/antipsychotics/CON155606_30.mdx
  learning/web/content/modules/antipsychotics/CON155606_38.mdx
  learning/web/content/modules/antipsychotics/CON155606_4.mdx
  learning/web/content/modules/antipsychotics/CON155606_43.mdx
  learning/web/content/modules/antipsychotics/CON155606_44.mdx
  learning/web/src/modules/modules.json
Labels: learning modules 🎓, r4r :eyes:

#138 Safety Public Assessment Reports links
  medicines/web/copy/about.md
  medicines/web/copy/homepage.md
Labels: r4r :eyes:, website 💻

#113 Search box
  medicines/web/components/disclaimer/index.tsx
  medicines/web/components/drug-index/index.tsx
  medicines/web/components/header/index.tsx
  medicines/web/components/mip/index.tsx
  medicines/web/components/page/index.tsx
  medicines/web/components/search-results/index.tsx
  medicines/web/components/search/index.tsx
  medicines/web/components/yellow-card/index.tsx
  medicines/web/styles/dimensions.ts
Labels: WIP 🚧

#142 More copy fixes
  learning/web/content/modules/benzodiazepines/CON234573_1.mdx
  learning/web/content/modules/benzodiazepines/CON234573_4.mdx
  learning/web/content/modules/benzodiazepines/CON234573_5.mdx
  learning/web/content/modules/benzodiazepines/CON234573_6.mdx
  learning/web/content/modules/opioids/CON143740_1.mdx
  learning/web/content/modules/opioids/CON143740_15.mdx
  learning/web/content/modules/ssri/CON146583_1.mdx
Labels: learning modules 🎓, r4r :eyes:

#125 Ensure footnotes in tables are displayed by duplicating them under the table.
  learning/import/learning_importer.py
  learning/web/content/modules/antipsychotics/CON155606_3.mdx
  learning/web/content/modules/antipsychotics/CON155606_31.mdx
  learning/web/content/modules/antipsychotics/CON155606_35.mdx
  learning/web/content/modules/antipsychotics/CON155606_39.mdx
  learning/web/content/modules/antipsychotics/CON155606_42.mdx
  learning/web/content/modules/antipsychotics/CON155606_45.mdx
  learning/web/content/modules/benzodiazepines/CON234573_11.mdx
  learning/web/content/modules/benzodiazepines/CON234573_13.mdx
  learning/web/content/modules/benzodiazepines/CON234573_19.mdx
  learning/web/content/modules/benzodiazepines/CON234573_2.mdx
  learning/web/content/modules/benzodiazepines/CON234573_23.mdx
  learning/web/content/modules/benzodiazepines/CON234573_3.mdx
  learning/web/content/modules/opioids/CON143740_12.mdx
  learning/web/content/modules/opioids/CON143740_13.mdx
  learning/web/content/modules/opioids/CON143740_16.mdx
  learning/web/content/modules/opioids/CON143740_19.mdx
  learning/web/content/modules/opioids/CON143740_3.mdx
  learning/web/content/modules/ssri/CON146583_21.mdx
  learning/web/content/modules/ssri/CON146583_27.mdx
  learning/web/content/modules/ssri/CON146583_28.mdx
  learning/web/content/modules/ssri/CON146583_3.mdx
  learning/web/content/modules/ssri/CON146583_4.mdx
Labels: great gif :clap:, learning modules 🎓, r4r :eyes:

#143 Replace contents pages with 'about this learning module' pages.
  learning/web/content/modules/antipsychotics/CON155606_1.mdx
  learning/web/content/modules/benzodiazepines/CON234573_1.mdx
  learning/web/content/modules/opioids/CON143740_1.mdx
  learning/web/content/modules/ssri/CON146583_1.mdx
  learning/web/src/modules/modules.json
Labels: learning modules 🎓, r4r :eyes:

#150 Learning content tweaks
  learning/web/content/modules/benzodiazepines/CON234573_10.mdx
  learning/web/content/modules/benzodiazepines/CON234573_18.mdx
  learning/web/content/modules/benzodiazepines/CON234573_2.mdx
  learning/web/content/modules/benzodiazepines/CON234573_4.mdx
  learning/web/content/modules/benzodiazepines/CON234573_6.mdx
  learning/web/content/modules/benzodiazepines/CON234573_7.mdx
  learning/web/content/modules/benzodiazepines/CON234573_8.mdx
  learning/web/content/modules/benzodiazepines/CON234573_9.mdx
  learning/web/content/modules/opioids/CON143740_15.mdx
Labels: learning modules 🎓

#157 Removing module evaluation pages
  learning/web/content/modules/antipsychotics/CON155606_46.mdx
  learning/web/content/modules/benzodiazepines/CON234573_24.mdx
  learning/web/content/modules/opioids/CON143740_18.mdx
  learning/web/content/modules/ssri/CON146583_29.mdx
  learning/web/src/modules/modules.json
Labels: learning modules 🎓, r4r :eyes:

#167 Remove disclaimer on no search results
  medicines/web/components/disclaimer/index.tsx
  medicines/web/components/search-results/index.tsx
Labels: enhancement 💫, r4r :eyes:

#164 Design review tweaks
  learning/web/content/modules/opioids/CON143740_17.mdx
  learning/web/src/components/Expander/index.js
  learning/web/src/components/Link/index.js
  learning/web/src/components/Sidebar/index.js
  learning/web/src/components/layout.js
  learning/web/src/templates/page.js
  learning/web/src/utils/colors.js
  learning/web/src/utils/mdx-components.js
  learning/web/src/utils/theme.js
Labels: learning modules 🎓

#153 Removing the word central and centrally
  medicines/web/components/search-results/index.tsx
  medicines/web/copy/about.md
Labels: r4r :eyes:

#173 A11y bugs
  .gitignore
  medicines/.gitignore
  medicines/web/.env
  medicines/web/.env.example
  medicines/web/components/disclaimer/index.tsx
  medicines/web/components/footer/index.tsx
  medicines/web/components/mip/index.tsx
  medicines/web/components/page/index.tsx
  medicines/web/components/search/index.tsx
  medicines/web/components/yellow-card/index.tsx
Labels: a11y :wheelchair:, bug, r4r :eyes:, website 💻

#166 Design tweaks review
  medicines/web/components/cookie-policy/index.tsx
  medicines/web/components/disclaimer/index.tsx
  medicines/web/components/search-results/index.tsx
  medicines/web/copy/cookies.md
Labels: r4r :eyes:, website 💻

#176 A couple of small bug fixes...
  medicines/web/components/search/index.tsx
Labels: r4r :eyes:, website 💻

#183 Ssri fix
  learning/web/content/modules/antipsychotics/CON155606_22.mdx
  learning/web/content/modules/antipsychotics/CON155606_3.mdx
  learning/web/content/modules/antipsychotics/CON155606_39.mdx
  learning/web/content/modules/benzodiazepines/CON234573_10.mdx
  learning/web/content/modules/benzodiazepines/CON234573_19.mdx
  learning/web/content/modules/benzodiazepines/CON234573_21.mdx
  learning/web/content/modules/benzodiazepines/CON234573_3.mdx
  learning/web/content/modules/ssri/CON146583_5.mdx
  learning/web/src/modules/modules.json
Labels: r4r :eyes:

#191 Fixes for #180
  learning/web/content/modules/antipsychotics/CON155606_41.mdx
  learning/web/content/modules/opioids/CON143740_7.mdx
Labels: learning modules 🎓

#193 Fix file links
  learning/web/gatsby-config.js
  learning/web/src/components/Link/index.js
Labels: learning modules 🎓

#198 Resolve Warning
  learning/web/src/components/CookieBanner/index.js
Labels: learning modules 🎓

#196 Small Style Fixes
  learning/web/src/components/Layout/index.js
  learning/web/src/components/SEO/index.js
  learning/web/src/components/Sidebar/index.js
  learning/web/src/pages/404.js
  learning/web/src/pages/index.js
  learning/web/src/templates/page.js
  learning/web/yarn.lock
Labels: learning modules 🎓

#201 Cookie policy, Privacy policy, Accessibility statement placeholder, and footer tidy-up
  learning/web/src/components/Layout/index.js
  learning/web/src/pages/accessibility.mdx
  learning/web/src/pages/cookies.mdx
Labels: learning modules 🎓

#121 Google Analytics / Tag Manager
  azure-pipelines.yml
  learning/web/content/modules/antipsychotics/about.mdx
  learning/web/content/modules/benzodiazepines/about.mdx
  learning/web/content/modules/opioids/about.mdx
  learning/web/content/modules/ssri/about.mdx
  learning/web/gatsby-config.js
  learning/web/package.json
  learning/web/src/modules/modules.json
  learning/web/yarn.lock
Labels: enhancement 💫, learning modules 🎓

#209 Fix display of search results in IE 11. Fixes issue #99.
  medicines/web/components/search-results/index.tsx
Labels: great gif :clap:

#222 Fix Mobile Nav
  learning/web/src/components/Sidebar/index.js
Labels: learning modules 🎓

#215 extract PL number into new metadata field
  medicines/Cargo.lock
  medicines/import/Cargo.toml
  medicines/import/src/hash.rs
  medicines/import/src/lib.rs
  medicines/import/src/metadata.rs
  medicines/import/src/par.rs
  medicines/import/src/report.rs
  medicines/import/src/spc_pil.rs
  medicines/import/src/storage.rs
  medicines/search/definitions/indexers/default.json
  medicines/search/definitions/indexes/default.json
  medicines/search/src/env.rs
  medicines/web/components/mip/index.tsx
  medicines/web/components/search/index.tsx
  medicines/web/services/azure-search.ts
Labels: cli tools :hammer_and_wrench:, enhancement 💫, r4r :eyes:

#197 CSP
  learning/web/gatsby-config.js
  learning/web/package.json
  learning/web/yarn.lock
  medicines/web/components/cookie-policy/index.tsx
  medicines/web/components/search-results/index.tsx
Labels: learning modules 🎓
