Repository MHRA/products, pull requests merged in 2020-04, with the labels that each got.

#600 Fix the state race condition
  medicines/doc-index-updater/src/document_manager/mod.rs
  medicines/doc-index-updater/src/state_manager/mod.rs
Labels: Great GIF :clap:

#604 Make test
  medicines/doc-index-updater/Makefile
  medicines/doc-index-updater/README.md
Labels: r4r :eyes:

#618 Log sftp file and dir info for debugging
  medicines/doc-index-updater/src/create_manager/sftp_client.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:, r4r :eyes:

#608 Defining behaviours in traits for testability
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/create_manager/models.rs
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/document_manager/mod.rs
  medicines/doc-index-updater/src/models.rs
  medicines/doc-index-updater/src/service_bus_client/mod.rs
  medicines/doc-index-updater/src/state_manager/mod.rs
  medicines/doc-index-updater/tests/create_manager.rs
  medicines/doc-index-updater/tests/delete_manager.rs
  medicines/doc-index-updater/tests/integration.rs
Labels: r4r :eyes:

#610 Make search tool use reqwest
  medicines/Cargo.lock
  medicines/Cargo.toml
  medicines/import/Cargo.lock
  medicines/search/Cargo.lock
  medicines/search/Cargo.toml
  medicines/search/src/azure_rest.rs
  medicines/search/src/datasource.rs
  medicines/search/src/index.rs
  medicines/search/src/indexer.rs
  medicines/search/src/lib.rs
  medicines/search/src/main.rs
Labels: BUG :bug:, r4r :eyes:

#622 Error log message that was missing
  medicines/doc-index-updater/src/document_manager/mod.rs
Labels: r4r :eyes:

#629 Basic README about Prometheus
  infrastructure/docs/logs.md
Labels: Documentation :memo:

#616 Adjust query parameters.
  medicines/web/src/components/drug-index/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/drug-index/index.tsx
  medicines/web/src/components/search-wrapper/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/search-wrapper/index.tsx
  medicines/web/src/components/structured-data/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/structured-data/index.tsx
  medicines/web/src/pages/index.tsx
  medicines/web/src/pages/product/index.tsx
  medicines/web/src/pages/search/index.tsx
  medicines/web/src/pages/substance-index/index.tsx
  medicines/web/src/pages/substance/index.tsx
  medicines/web/src/tools/sitemap-generator.ts
Labels: Data Analysis :nerd_face:, r4r :eyes:

#635 Set delegate credentials to yes in ssh config file
  medicines/doc-index-updater/Dockerfile
Labels: r4r :eyes:

#640 Test get blob from content id
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/search_client/mod.rs
  medicines/doc-index-updater/src/service_bus_client/mod.rs
Labels: Tech task :computer_mouse:

#625 Log error when reading queue fails
  medicines/doc-index-updater/src/service_bus_client/mod.rs
Labels: Great GIF :clap:, r4r :eyes:

#645 Convert products array to csv string
  medicines/doc-index-updater/src/create_manager/models.rs
Labels: BUG :bug:, EPIC - Auto Batch Process :oncoming_automobile:

#644 Better documentation for viewing logs
  infrastructure/docs/logs.md
Labels: Documentation :memo:

#654 Return an error if adding a message to the service bus fails
  medicines/doc-index-updater/src/document_manager/mod.rs
Labels: Great GIF :clap:

#663 Replace two spaces with tab in makefile
  medicines/doc-index-updater/Makefile
Labels: r4r :eyes:

#675 Add CORS support to API
  medicines/api/Cargo.lock
  medicines/api/Cargo.toml
  medicines/api/src/main.rs
Labels: Great GIF :clap:

#676 Mutex get status
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/state_manager/mod.rs
Labels: Automated Tests :robot:, r4r :eyes:

#672 Delete workflow should always result in a consistent state
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/service_bus_client/mod.rs
  medicines/doc-index-updater/src/storage_client/mod.rs
  medicines/search-client/Cargo.lock
  medicines/search-client/Cargo.toml
  medicines/search-client/src/lib.rs
  medicines/search-client/src/models.rs
Labels: r4r :eyes:

#661 add hello world example
  .github/workflows/hello-world.yaml
  hello-world/.dockerignore
  hello-world/Cargo.lock
  hello-world/Cargo.toml
  hello-world/Dockerfile
  hello-world/Makefile
  hello-world/README.md
  hello-world/src/lib.rs
  hello-world/src/main.rs
  hello-world/tests/hello_world.rs
Labels: r4r :eyes:

#685 clippy warnings
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/tests/integration.rs
  medicines/doc-index-updater/tests/support/document_api.rs
Labels: r4r :eyes:

#684 Put API key in header in search client
  medicines/search-client/src/lib.rs
Labels: BUG :bug:

#706 added warp recovery for correct status codes
  medicines/doc-index-updater/src/main.rs
Labels: BUG :bug:, r4r :eyes:

#705 Change to use GITHUB_SHA variable
  .github/workflows/doc-index-updater-release.yaml
Labels: BUG :bug:, EPIC - Auto Batch Process :oncoming_automobile:, r4r :eyes:

#714 Product page api
  medicines/api/src/document.rs
  medicines/api/src/product.rs
  medicines/api/src/schema.rs
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/search-client/src/lib.rs
  medicines/search-client/src/models.rs
Labels: EPIC - API Pod :radio:

#721 Docker BuildKit
  hello-world/Cargo.lock
  hello-world/Dockerfile
  hello-world/Makefile
  infrastructure/environments/kind/README.md
  medicines/api/Makefile
  medicines/api/README.md
  medicines/doc-index-updater-stub/README.md
  medicines/doc-index-updater/Dockerfile
  medicines/doc-index-updater/Makefile
  medicines/doc-index-updater/README.md
  medicines/doc-index-updater/scripts/README.md
  medicines/import/README.md
  medicines/search/README.md
  medicines/web/README.md
Labels: r4r :eyes:

#730 Add document type filter to API interface
  medicines/api/src/schema.rs
Labels: EPIC - API Pod :radio:

#731 Multi level filtering
  medicines/api/src/document.rs
  medicines/api/src/product.rs
  medicines/api/src/substance.rs
Labels: EPIC - API Pod :radio:

#729 Fix subtances API for when products contain multiple substances
  medicines/api/Cargo.lock
  medicines/api/Cargo.toml
  medicines/api/src/substance.rs
Labels: EPIC - API Pod :radio:

#734 Fix parsing Basic Auth creds
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/auth_manager/mod.rs
Labels: r4r :eyes:

#293 Remove Zeebe manifests
  infrastructure/environments/kind/Makefile
  infrastructure/environments/kind/README.md
  infrastructure/environments/kind/config.yaml
Labels: r4r :eyes:

#719 Basic GraphQl products page
  medicines/web/src/components/search-results/index.tsx
  medicines/web/src/model/substance.ts
  medicines/web/src/pages/product/index.tsx
  medicines/web/src/services/documents-loader.ts
  medicines/web/src/services/results-converter.ts
Labels: EPIC - API Pod :radio:, Website 💻, r4r :eyes:

#742 Timlee/fix learning site deploy
  .github/workflows/learning-web-master.yaml
  .github/workflows/learning-web-release.yaml
Labels: BUG :bug:
