Repository MHRA/products, pull requests merged in 2020-03, with the labels that each got.

#461 Friendlier PR template
  .github/pull_request_template.md
Labels: Documentation :memo:

#460 Log bad errors
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/src/state_manager/mod.rs
  medicines/doc-index-updater/src/state_manager/redis.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#466 Redis SET does not give JobStatus return value
  medicines/doc-index-updater/src/state_manager/mod.rs
  medicines/doc-index-updater/src/state_manager/redis.rs
Labels: BUG :bug:

#472 Service bus client
  infrastructure/environments/development/outputs.tf
  infrastructure/modules/service-bus/main.tf
  infrastructure/modules/service-bus/output.tf
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/lib.rs
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/src/service_bus_client/mod.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#449 Delete service message
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/lib.rs
  medicines/doc-index-updater/src/models.rs
  medicines/doc-index-updater/src/state_manager/mod.rs
  medicines/doc-index-updater/src/state_manager/redis.rs
  medicines/doc-index-updater/tests/integration.rs
  medicines/doc-index-updater/tests/support.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:, HIGH PRIORITY :arrow_double_up:, infrastructure :building_construction:, r4r :eyes:

#474 Health probes
  azure-pipelines.yml
  infrastructure/environments/development/control-plane.yml
  medicines/doc-index-updater/examples/istio/controlplane.yaml
  medicines/doc-index-updater/examples/istio/istio.sh
  medicines/doc-index-updater/examples/manifests/base/deployment.yaml
  medicines/doc-index-updater/examples/manifests/base/destination-rule.yaml
  medicines/doc-index-updater/examples/manifests/base/kustomization.yaml
Labels: r4r :eyes:

#473 Delete Manager Retrieves Delete Demands
  medicines/doc-index-updater/.env.example
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/README.md
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/lib.rs
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/src/service_bus_client/mod.rs
  medicines/doc-index-updater/tests/delete_manager.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#462 Dispatch update & delete events to service bus
  .gitignore
  medicines/.gitignore
  medicines/doc-index-updater-stub/README.md
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/examples/manifests/README.md
  medicines/doc-index-updater/examples/manifests/base/deployment.yaml
  medicines/doc-index-updater/examples/manifests/overlays/development/deployment.yaml
  medicines/doc-index-updater/examples/sealed-secrets/SealedSecret-create-queue-key.yaml
  medicines/doc-index-updater/examples/sealed-secrets/SealedSecret-delete-queue-key.yaml
  medicines/doc-index-updater/src/document_manager/mod.rs
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/tests/integration.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:, WIP 🚧

#467 Improve cookie settings on CPD site
  azure-pipelines.yml
  learning/web/README.md
  learning/web/cypress/integration/spec.js
  learning/web/gatsby-config.js
  learning/web/package.json
  learning/web/src/components/CookieBanner/index.js
  learning/web/src/components/Layout/index.js
  learning/web/src/pages/cookies.js
  learning/web/src/pages/cookies.mdx
  learning/web/src/pages/index.js
  learning/web/yarn.lock
Labels: EPIC - Learning Modules 🎓, Website 💻, r4r :eyes:

#476 Much better integration test for the service bus
  medicines/doc-index-updater/.env.example
  medicines/doc-index-updater/tests/delete_manager.rs
Labels: Automated Tests :robot:, EPIC - Auto Batch Process :oncoming_automobile:

#454 Products API
  medicines/api/Cargo.lock
  medicines/api/Cargo.toml
  medicines/api/src/azure_search.rs
  medicines/api/src/product.rs
  medicines/api/src/schema.rs
Labels: EPIC - API Pod :radio:, Great GIF :clap:, r4r :eyes:

#258 Add drug and substance structured data to site
  medicines/web/infrastructure/README.md
  medicines/web/package.json
  medicines/web/src/components/search-results/index.tsx
  medicines/web/src/components/structured-data/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/structured-data/index.test.tsx
  medicines/web/src/components/structured-data/index.tsx
  medicines/web/src/pages/product/index.tsx
  medicines/web/src/pages/substance-index/index.tsx
  medicines/web/src/pages/substance/index.tsx
  medicines/web/yarn.lock
Labels: Great GIF :clap:

#475 Timlee/stop ga reinitialisation
  medicines/web/src/components/page/index.tsx
  medicines/web/src/components/search-wrapper/index.tsx
  medicines/web/src/pages/_app.tsx
  medicines/web/src/services/events.ts
Labels: BUG :bug:, Data Analysis :nerd_face:, r4r :eyes:

#482 DocIndexUpdaterQueue
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/document_manager/mod.rs
  medicines/doc-index-updater/src/models.rs
  medicines/doc-index-updater/src/service_bus_client/mod.rs
  medicines/doc-index-updater/tests/create_manager.rs
  medicines/doc-index-updater/tests/delete_manager.rs
  medicines/doc-index-updater/tests/integration.rs
  medicines/doc-index-updater/tests/support/mod.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#463 Use debug parameter to make debug script optional
  azure-pipelines.yml
  medicines/web/.env.example
  medicines/web/Dockerfile
  medicines/web/README.md
  medicines/web/docker-compose.yml
  medicines/web/next.config.js
  medicines/web/src/services/events.ts
Labels: BUG :bug:, Data Analysis :nerd_face:, Website 💻

#481 Add loading message to search results and product results page
  medicines/web/src/components/search-results/index.test.tsx
  medicines/web/src/components/search-results/index.tsx
  medicines/web/src/pages/product/index.tsx
  medicines/web/src/pages/search/index.tsx
  medicines/web/yarn.lock
Labels: Website 💻, r4test :microscope:

#484 SFTP for Doc-Index-Updater
  medicines/doc-index-updater/.env.example
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/create_manager/sftp_client.rs
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/src/models.rs
  medicines/doc-index-updater/src/service_bus_client/mod.rs
  medicines/doc-index-updater/tests/create_manager.rs
  medicines/doc-index-updater/tests/delete_manager.rs
  medicines/doc-index-updater/tests/support/mod.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#479 Delete Service Delete Blob
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/lib.rs
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/src/search/mod.rs
  medicines/doc-index-updater/src/storage_client/mod.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#488 Create User Story.md
  .github/ISSUE_TEMPLATE/User Story.md
Labels: Documentation :memo:

#489 Update User Story.md
  .github/ISSUE_TEMPLATE/User Story.md
Labels: Documentation :memo:

#495 Error message for install redis when running tests
  medicines/doc-index-updater/tests/support/mod.rs
Labels: Automated Tests :robot:

#496 Remove messages on success
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/service_bus_client/mod.rs
  medicines/doc-index-updater/tests/create_manager.rs
  medicines/doc-index-updater/tests/delete_manager.rs
  medicines/doc-index-updater/tests/integration.rs
  medicines/doc-index-updater/tests/support/mod.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#501 Added missing env.example entries
  medicines/doc-index-updater/.env.example
Labels: Documentation :memo:, EPIC - Auto Batch Process :oncoming_automobile:

#499 Create metadata from message contents
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/create_manager/metadata.rs
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/lib.rs
  medicines/doc-index-updater/src/models.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:, r4r :eyes:

#494 Delete from Index
  medicines/doc-index-updater/.env.example
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/lib.rs
  medicines/doc-index-updater/src/search/mod.rs
  medicines/doc-index-updater/src/search_client/mod.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:, r4r :eyes:

#502 Support XML requests for Sentinel
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/document_manager/mod.rs
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/src/models.rs
  medicines/doc-index-updater/tests/integration.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:, r4r :eyes:

#513 Fix fuzzy search for product licences
  medicines/web/src/services/search-query-normalizer.test.ts
  medicines/web/src/services/search-query-normalizer.ts
Labels: BUG :bug:, Website 💻, r4r :eyes:

#503 Amend Github action to build, test, push and deploy Docker image
  .github/workflows/doc-index-updater.yaml
  infrastructure/.env.example
  infrastructure/docs/destroy-provision-aks.md
  infrastructure/environments/development/.env.example
  infrastructure/environments/development/main.tf
  infrastructure/environments/non-prod/.env.example
  infrastructure/environments/non-prod/main.tf
  infrastructure/environments/prod/.env.example
  infrastructure/modules/products/main.tf
  infrastructure/modules/service-bus/variables.tf
  medicines/doc-index-updater/.env.example
  medicines/doc-index-updater/Dockerfile
  medicines/doc-index-updater/Makefile
  medicines/doc-index-updater/README.md
  medicines/doc-index-updater/examples/README.md
  medicines/doc-index-updater/examples/istio/README.md
  medicines/doc-index-updater/examples/istio/istio-delete.sh
  medicines/doc-index-updater/examples/istio/istio.sh
  medicines/doc-index-updater/examples/local-cluster/README.md
  medicines/doc-index-updater/examples/local-cluster/kind.sh
  medicines/doc-index-updater/examples/manifests/README.md
  medicines/doc-index-updater/examples/manifests/base/deployment.yaml
  medicines/doc-index-updater/examples/manifests/base/destination-rule.yaml
  medicines/doc-index-updater/examples/manifests/base/egress.yaml
  medicines/doc-index-updater/examples/manifests/base/ingress.yaml
  medicines/doc-index-updater/examples/manifests/base/kustomization.yaml
  medicines/doc-index-updater/examples/manifests/base/namespace.yaml
  medicines/doc-index-updater/examples/manifests/base/service.yaml
  medicines/doc-index-updater/examples/manifests/overlays/development/SealedSecret-create-queue-key.yaml
  medicines/doc-index-updater/examples/manifests/overlays/development/SealedSecret-delete-queue-key.yaml
  medicines/doc-index-updater/examples/manifests/overlays/development/SealedSecret-redis-key.yaml
  medicines/doc-index-updater/examples/manifests/overlays/development/deployment.yaml
  medicines/doc-index-updater/examples/manifests/overlays/development/ingress.yaml
  medicines/doc-index-updater/examples/manifests/overlays/development/kustomization.yaml
  medicines/doc-index-updater/examples/manifests/overlays/local/kustomization.yaml
  medicines/doc-index-updater/examples/sealed-secrets/.gitignore
  medicines/doc-index-updater/examples/sealed-secrets/ClusterRole-secrets-unsealer.yaml
  medicines/doc-index-updater/examples/sealed-secrets/ClusterRoleBinding-sealed-secrets-controller.yaml
  medicines/doc-index-updater/examples/sealed-secrets/CustomResourceDefinition-sealedsecrets.bitnami.com.yaml
  medicines/doc-index-updater/examples/sealed-secrets/Deployment-sealed-secrets-controller.yaml
  medicines/doc-index-updater/examples/sealed-secrets/README.md
  medicines/doc-index-updater/examples/sealed-secrets/Role-sealed-secrets-key-admin.yaml
  medicines/doc-index-updater/examples/sealed-secrets/Role-sealed-secrets-service-proxier.yaml
  medicines/doc-index-updater/examples/sealed-secrets/RoleBinding-sealed-secrets-controller.yaml
  medicines/doc-index-updater/examples/sealed-secrets/RoleBinding-sealed-secrets-service-proxier.yaml
  medicines/doc-index-updater/examples/sealed-secrets/Service-sealed-secrets-controller.yaml
  medicines/doc-index-updater/examples/sealed-secrets/ServiceAccount-sealed-secrets-controller.yaml
  medicines/doc-index-updater/examples/sealed-secrets/controller.yaml
  medicines/doc-index-updater/examples/sealed-secrets/kustomization.yaml
  medicines/doc-index-updater/src/create_manager/metadata.rs
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/create_manager/sftp_client.rs
  medicines/doc-index-updater/src/document_manager/mod.rs
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/src/search_client/mod.rs
  medicines/doc-index-updater/tests/integration.rs
  medicines/import/src/csv.rs
  medicines/import/src/main.rs
  medicines/import/src/metadata.rs
  medicines/import/tests/hash_test.rs
Labels: infrastructure :building_construction:

#515 Clear cookies by setting path and domain
  azure-pipelines.yml
  medicines/web/.env.example
  medicines/web/Dockerfile
  medicines/web/README.md
  medicines/web/docker-compose.yml
  medicines/web/next.config.js
  medicines/web/src/components/cookie-form/index.tsx
Labels: BUG :bug:, Website 💻, r4r :eyes:

#506 Upload file to blob storage
  medicines/doc-index-updater/src/create_manager/hash.rs
  medicines/doc-index-updater/src/create_manager/metadata.rs
  medicines/doc-index-updater/src/create_manager/mod.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:, r4r :eyes:

#516 #483 DataLayer pushes carry the date
  medicines/web/src/services/events.ts
Labels: Data Analysis :nerd_face:, Website 💻

#510 Using into() for XMLDocument
  medicines/doc-index-updater/src/document_manager/mod.rs
  medicines/doc-index-updater/src/models.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#529 K8's creds update script
  infrastructure/scripts/update-kubernetes-config.sh
Labels: CLI tools :hammer_and_wrench:, EPIC - Auto Batch Process :oncoming_automobile:, Internal :inbox_tray:

#514 Timlee/fix search for percent
  medicines/web/src/components/search-wrapper/index.tsx
  medicines/web/src/services/search-query-normalizer.test.ts
  medicines/web/src/services/search-query-normalizer.ts
Labels: BUG :bug:, Website 💻, r4test :microscope:

#532 Minimist upgrade security fix
  medicines/web/yarn.lock
Labels: BUG :bug:, Website 💻

#522 Create service updates index
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/create_manager/models.rs
  medicines/doc-index-updater/src/create_manager/search_index.rs
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/search_client/mod.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#528 Adding Basic Auth to the doc index updater
  medicines/doc-index-updater/.env.example
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/auth_manager/mod.rs
  medicines/doc-index-updater/src/document_manager/mod.rs
  medicines/doc-index-updater/src/health.rs
  medicines/doc-index-updater/src/lib.rs
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/src/state_manager/mod.rs
  medicines/doc-index-updater/tests/integration.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:, WIP 🚧

#542 Health check endpoints shouldn't use auth.
  medicines/doc-index-updater/src/health.rs
Labels: BUG :bug:, EPIC - Auto Batch Process :oncoming_automobile:

#233 CDN infrastructure
  infrastructure/environments/non-prod/outputs.tf
  infrastructure/environments/prod/main.tf
  infrastructure/environments/prod/outputs.tf
  infrastructure/environments/prod/variables.tf
  infrastructure/modules/cpd/main.tf
  infrastructure/modules/products/main.tf
Labels: r4r :eyes:

#546 /healthz returns a blank response (204).
  medicines/doc-index-updater/src/health.rs
  medicines/doc-index-updater/src/main.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:, Enhancement 💫, r4r :eyes:

#526 move cluster to the correct subnet
  infrastructure/docs/infrastructure.md
  infrastructure/docs/kubernetes.md
  infrastructure/environments/development/.env.example
  infrastructure/environments/development/main.tf
  infrastructure/environments/development/outputs.tf
  infrastructure/environments/development/variables.tf
  infrastructure/environments/non-prod/main.tf
  infrastructure/environments/non-prod/outputs.tf
  infrastructure/environments/non-prod/variables.tf
  infrastructure/environments/prod/.env.example
  infrastructure/environments/prod/main.tf
  infrastructure/environments/prod/outputs.tf
  infrastructure/environments/prod/variables.tf
  infrastructure/modules/cluster/main.tf
  infrastructure/modules/cluster/variables.tf
  infrastructure/modules/cpd/main.tf
  infrastructure/modules/cpd/output.tf
  infrastructure/modules/products/main.tf
  infrastructure/modules/products/outputs.tf
Labels: r4r :eyes:

#552 Azure monitor
  .gitignore
  infrastructure/modules/cluster/main.tf
  infrastructure/scripts/create-storage-account.sh
Labels: r4r :eyes:

#555 Sftp connection failure is non fatal
  medicines/doc-index-updater/src/create_manager/sftp_client.rs
Labels: BUG :bug:

#547 Added correlation ids to log messages
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/search_client/mod.rs
  medicines/doc-index-updater/src/service_bus_client/mod.rs
  medicines/doc-index-updater/src/state_manager/redis.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#559 Cluster terraform tweaks
  azure-pipelines.yml
  infrastructure/docs/destroy-provision-aks.md
  infrastructure/docs/infrastructure.md
  infrastructure/modules/cluster/main.tf
Labels: r4r :eyes:

#563 Removing is_deleted from index
  medicines/doc-index-updater/src/create_manager/models.rs
Labels: BUG :bug:

#566 Sanitise fields
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/create_manager/models.rs
  medicines/doc-index-updater/src/create_manager/sanitiser.rs
  medicines/doc-index-updater/src/create_manager/search_index.rs
Labels: BUG :bug:

#567 Github Actions
  .github/workflows/doc-index-updater-branch.yaml
  .github/workflows/doc-index-updater-master.yaml
  .github/workflows/learning-web-branch.yaml
  .github/workflows/learning-web-master.yaml
  .github/workflows/medicines-web-branch.yaml
  .github/workflows/medicines-web-master.yaml
  infrastructure/environments/non-prod/main.tf
  medicines/web/package.json
  medicines/web/yarn.lock
Labels: r4r :eyes:

#573 sanitising in the facets
  medicines/doc-index-updater/src/create_manager/models.rs
  medicines/doc-index-updater/src/create_manager/sanitiser.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#583 Get job status XML endpoint
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/src/state_manager/mod.rs
Labels: HIGH PRIORITY :arrow_double_up:

#578 Add fuzzy search functionality back in
  medicines/web/cypress/integration/tests.js
  medicines/web/src/services/search-query-normalizer.test.ts
  medicines/web/src/services/search-query-normalizer.ts
Labels: Website 💻

#595 Correctly parse PL number when converting from Document to BlobMetadata.
  medicines/doc-index-updater/src/create_manager/models.rs
  medicines/doc-index-updater/src/create_manager/sanitiser.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:, r4r :eyes:
