Repository MHRA/products, pull requests merged in 2020-02, with the labels that each got.

#285 HOTFIX: Change AZ Pipeline virtual machine version
  azure-pipelines.yml
Labels: bug, high priority, infrastructure :building_construction:, r4r :eyes:

#281 API Pod - Pipeline
  medicines/api/azure-pipelines.yaml
Labels: API 🦀, WIP 🚧, cli tools :hammer_and_wrench:, enhancement 💫, infrastructure :building_construction:

#265 GraphQL schema with pagination
  medicines/api/Cargo.lock
  medicines/api/Cargo.toml
  medicines/api/README.md
  medicines/api/src/azure_search.rs
  medicines/api/src/main.rs
  medicines/api/src/pagination.rs
  medicines/api/src/product.rs
  medicines/api/src/schema.rs
  medicines/api/src/substance.rs
Labels: API 🦀

#282 TESTS - Enzyme tests for the React components of the Products site
  azure-pipelines.yml
  medicines/web/.gitignore
  medicines/web/config/assets-transformer.ts
  medicines/web/config/enzyme.ts
  medicines/web/jest.config.js
  medicines/web/jest.tsconfig.json
  medicines/web/package.json
  medicines/web/src/components/cookie-policy/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/cookie-policy/index.test.tsx
  medicines/web/src/components/disclaimer/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/disclaimer/index.test.tsx
  medicines/web/src/components/drug-index/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/drug-index/index.test.tsx
  medicines/web/src/components/footer/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/footer/index.test.tsx
  medicines/web/src/components/header/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/header/index.test.tsx
  medicines/web/src/components/mip-text/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/mip-text/index.test.tsx
  medicines/web/src/components/mip-text/index.tsx
  medicines/web/src/components/mip/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/mip/index.test.tsx
  medicines/web/src/components/page/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/page/index.test.tsx
  medicines/web/src/components/pdf/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/pdf/index.test.tsx
  medicines/web/src/components/search-results/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/search-results/index.test.tsx
  medicines/web/src/components/search/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/search/index.test.tsx
  medicines/web/src/components/yellow-card/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/yellow-card/index.test.tsx
  medicines/web/tsconfig.json
  medicines/web/typings.d.ts
  medicines/web/yarn.lock
Labels: enhancement 💫, r4r :eyes:, website 💻

#284 Add stub document manager
  medicines/document-manager/README.md
  medicines/document-manager/stub-api/.dockerignore
  medicines/document-manager/stub-api/.gitignore
  medicines/document-manager/stub-api/Dockerfile
  medicines/document-manager/stub-api/README.md
  medicines/document-manager/stub-api/cpanfile
  medicines/document-manager/stub-api/cpanfile.snapshot
  medicines/document-manager/stub-api/stub.pl
Labels: API 🦀, r4r :eyes:

#287 API Pod - Pipeline
  medicines/api/README.md
  medicines/api/azure-pipelines.yaml
  medicines/api/azure-pipelines.yml
Labels: API 🦀, cli tools :hammer_and_wrench:, enhancement 💫, infrastructure :building_construction:

#294 Match all keywords in Search
  medicines/web/cypress/integration/tests.js
  medicines/web/src/services/azure-search.ts
Labels: enhancement 💫

#303 #302 Fixing trailing character search error
  medicines/web/src/services/azure-search.ts
Labels: bug, website 💻

#304 Kubernetes deployments for stub api
  medicines/document-manager/README.md
  medicines/document-manager/stub-api/README.md
  medicines/document-manager/stub-api/manifests/cert.yaml
  medicines/document-manager/stub-api/manifests/cluster-issuer.yaml
  medicines/document-manager/stub-api/manifests/deployment.yaml
  medicines/document-manager/stub-api/manifests/ingress.yaml
  medicines/document-manager/stub-api/manifests/svc.yaml
  medicines/document-manager/stub-api/stub.pl
Labels: API 🦀, infrastructure :building_construction:, r4r :eyes:

#307 Data Layer Page Categories
  medicines/web/package.json
  medicines/web/src/components/mip/index.tsx
  medicines/web/src/components/pdf/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/pdf/index.tsx
  medicines/web/src/pages/_app.tsx
  medicines/web/src/pages/about.tsx
  medicines/web/src/pages/accessibility.tsx
  medicines/web/src/pages/cookies.tsx
  medicines/web/src/services/events.ts
  medicines/web/yarn.lock
Labels: data analytics :nerd_face:, website 💻

#283 Timlee/update documentation
  DEPLOY.md
  README.md
  docs/principles/README.md
  docs/principles/cloud-native.md
  docs/principles/cloud.md
  docs/principles/devops.md
  docs/principles/microservices.md
  docs/principles/risks.md
  docs/principles/security.md
  docs/principles/service-mesh.md
  docs/principles/testing.md
  infrastructure/.env.example
  learning/README.md
  learning/docs/contributor-guidelines/README.md
  learning/docs/contributor-guidelines/code-of-conduct.md
  medicines/.gitignore
  medicines/README.md
  medicines/docs/architecture.svg
  medicines/docs/architecture/README.md
  medicines/docs/architecture/architecture_partial.svg
  medicines/docs/architecture/architecture_v0.2.svg
  medicines/docs/contributor-guidelines/README.md
  medicines/docs/contributor-guidelines/code-of-conduct.md
  medicines/docs/data/README.md
  medicines/web/README.md
  medicines/web/package.json
Labels: documentation, r4r :eyes:

#279 Improved Privacy Settings
  medicines/web/cypress/integration/tests.js
  medicines/web/package.json
  medicines/web/src/components/cookie-form/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/cookie-form/index.test.tsx
  medicines/web/src/components/cookie-form/index.tsx
  medicines/web/src/components/cookie-policy/index.test.tsx
  medicines/web/src/components/cookie-policy/index.tsx
  medicines/web/src/components/page/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/page/index.test.tsx
  medicines/web/src/components/page/index.tsx
  medicines/web/src/components/search-results/index.tsx
  medicines/web/src/copy/cookies-table.md
  medicines/web/src/copy/cookies.md
  medicines/web/src/hooks/index.tsx
  medicines/web/src/pages/_app.tsx
  medicines/web/src/pages/about.tsx
  medicines/web/src/pages/accessibility.tsx
  medicines/web/src/pages/cookies.tsx
  medicines/web/src/pages/index.tsx
  medicines/web/yarn.lock
Labels: enhancement 💫, r4r :eyes:, website 💻

#254 Filters
  medicines/web/config/env.ts
  medicines/web/cypress/fixtures/search_results.spc.json
  medicines/web/cypress/fixtures/search_results.spc.page2.json
  medicines/web/cypress/fixtures/search_results.spcpil.json
  medicines/web/cypress/integration/tests.js
  medicines/web/jest.config.js
  medicines/web/src/components/mip/index.tsx
  medicines/web/src/components/search-filter/index.tsx
  medicines/web/src/components/search-results/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/search-results/__snapshots__/pagination.test.tsx.snap
  medicines/web/src/components/search-results/index.test.tsx
  medicines/web/src/components/search-results/index.tsx
  medicines/web/src/components/search-results/pagination.test.tsx
  medicines/web/src/components/search-results/pagination.tsx
  medicines/web/src/services/azure-search.ts
  medicines/web/src/services/events.ts
  medicines/web/src/services/querysting-interpreter.test.ts
  medicines/web/src/services/querystring-interpreter.ts
  medicines/web/src/services/results-converter.ts
  medicines/web/src/services/search-query-normalizer.test.ts
  medicines/web/src/services/search-query-normalizer.ts
  medicines/web/tsconfig.json
Labels: Great GIF :clap:

#306 API Pipeline secrets 🕵️‍♂️
  infrastructure/docs/kubernetes.md
  infrastructure/environments/development/control-plane.yml
  medicines/api/Dockerfile
  medicines/api/README.md
  medicines/api/docker-compose.yml
  medicines/api/infrastructure/development/.env.example
  medicines/api/infrastructure/development/deployment.yml
  medicines/api/infrastructure/non-prod/.env.example
  medicines/api/infrastructure/production/.env.example
Labels: CLI tools :hammer_and_wrench:, EPIC - API Pod :radio:, Enhancement 💫, Great GIF :clap:, infrastructure :building_construction:, r4r :eyes:

#428 DataLayer: previousEvent and pageCategory
  medicines/web/src/services/events.ts
Labels: Data Analysis :nerd_face:, Great GIF :clap:

#388 TESTS - Enzyme tests for the React components learning
  azure-pipelines.yml
  learning/web/config/__mocks__/gatsby.js
  learning/web/config/enzyme.js
  learning/web/config/file-mock.js
  learning/web/config/jest-preprocess.js
  learning/web/config/loadershim.js
  learning/web/config/mock-gatsby.js
  learning/web/jest.config.js
  learning/web/package.json
  learning/web/src/components/CookieBanner/__snapshots__/index.test.js.snap
  learning/web/src/components/CookieBanner/index.test.js
  learning/web/src/components/Expander/__snapshots__/index.test.js.snap
  learning/web/src/components/Expander/index.test.js
  learning/web/src/components/Layout/__snapshots__/index.test.js.snap
  learning/web/src/components/Layout/index.test.js
  learning/web/src/components/Link/__snapshots__/index.test.js.snap
  learning/web/src/components/Link/index.test.js
  learning/web/src/components/SEO/__snapshots__/index.test.js.snap
  learning/web/src/components/SEO/index.test.js
  learning/web/src/components/Sidebar/__snapshots__/index.test.js.snap
  learning/web/src/components/Sidebar/index.test.js
  learning/web/yarn.lock
Labels: CLI tools :hammer_and_wrench:, EPIC - Learning Modules 🎓, Enhancement 💫, STORY :book:, r4r :eyes:

#438 Doc-index-updater basic structure
  medicines/Cargo.toml
  medicines/doc-index-updater/.gitignore
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/lib.rs
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/src/state_manager/mod.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#440 Update Stub API to use Job Lookups & Provide Lookup URLs
  medicines/document-manager/stub-api/Dockerfile
  medicines/document-manager/stub-api/README.md
  medicines/document-manager/stub-api/cpanfile
  medicines/document-manager/stub-api/manifests/deployment.yaml
  medicines/document-manager/stub-api/stub.pl
Labels: EPIC - Auto Batch Process :oncoming_automobile:, HIGH PRIORITY :arrow_double_up:

#445 Add basic auth to stub api
  medicines/document-manager/stub-api/Dockerfile
  medicines/document-manager/stub-api/README.md
  medicines/document-manager/stub-api/cpanfile
  medicines/document-manager/stub-api/manifests/deployment.yaml
  medicines/document-manager/stub-api/stub.pl
Labels: EPIC - Auto Batch Process :oncoming_automobile:, HIGH PRIORITY :arrow_double_up:

#444 Redis state manager
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/lib.rs
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/src/models.rs
  medicines/doc-index-updater/src/state_manager/mod.rs
  medicines/doc-index-updater/src/state_manager/redis.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#448 Service Bus Update 🚌
  infrastructure/modules/service-bus/main.tf
Labels: EPIC - Auto Batch Process :oncoming_automobile:, Tech Infrastructure, infrastructure :building_construction:, r4r :eyes:

#453 Add health endpoint to stub document manager.
  medicines/doc-index-updater-stub/.dockerignore
  medicines/doc-index-updater-stub/.gitignore
  medicines/doc-index-updater-stub/Dockerfile
  medicines/doc-index-updater-stub/README.md
  medicines/doc-index-updater-stub/cpanfile
  medicines/doc-index-updater-stub/cpanfile.snapshot
  medicines/doc-index-updater-stub/manifests/cert.yaml
  medicines/doc-index-updater-stub/manifests/cluster-issuer.yaml
  medicines/doc-index-updater-stub/manifests/deployment.yaml
  medicines/doc-index-updater-stub/manifests/ingress.yaml
  medicines/doc-index-updater-stub/manifests/svc.yaml
  medicines/doc-index-updater-stub/stub.pl
  medicines/document-manager/README.md
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#456 Add Document Manager API
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/document_manager/mod.rs
  medicines/doc-index-updater/src/health.rs
  medicines/doc-index-updater/src/lib.rs
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/src/models.rs
  medicines/doc-index-updater/src/state_manager/mod.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:

#459 Update stub API to reflect desired output of real API.
  medicines/doc-index-updater-stub/README.md
  medicines/doc-index-updater-stub/manifests/cert.yaml
  medicines/doc-index-updater-stub/manifests/cluster-issuer.yaml
  medicines/doc-index-updater-stub/manifests/ingress.yaml
  medicines/doc-index-updater-stub/manifests/svc.yaml
  medicines/doc-index-updater-stub/stub.pl
Labels: EPIC - Auto Batch Process :oncoming_automobile:
