Repository MHRA/products, pull requests merged in 2020-05, with the labels that each got.

#750 Reduce Azure calls in the API
  medicines/api/src/document.rs
  medicines/api/src/pagination.rs
  medicines/api/src/product.rs
  medicines/api/src/schema.rs
  medicines/api/src/substance.rs
  medicines/search-client/src/lib.rs
Labels: EPIC - API Pod :radio:

#753 DocumentType in search results graphql variable
  medicines/web/src/services/search-results-loader.ts
Labels: BUG :bug:, EPIC - API Pod :radio:

#764 Spelling
  .github/workflows/check-spelling.yaml
  DEPLOY.md
  docs/principles/cloud-native.md
  docs/principles/cloud.md
  docs/principles/testing.md
  docs/words.txt
  infrastructure/docs/infrastructure.md
  infrastructure/docs/kubernetes.md
  infrastructure/docs/logs.md
  medicines/api/README.md
  medicines/doc-index-updater-stub/README.md
  medicines/doc-index-updater/README.md
  spellcheck.yaml
Labels: r4r :eyes:

#773 add k8s rbac
  infrastructure/modules/cluster/main.tf
Labels: r4r :eyes:

#770 pars-upload-branch workflow
  .github/workflows/pars-upload-branch.yaml
  medicines/pars-upload/.babelrc
  medicines/pars-upload/.pa11yci
  medicines/pars-upload/.prettierrc.json
  medicines/pars-upload/cypress.json
  medicines/pars-upload/cypress/integration/tests.js
  medicines/pars-upload/cypress/plugins/index.js
  medicines/pars-upload/cypress/support/commands.js
  medicines/pars-upload/cypress/support/index.js
  medicines/pars-upload/jest.config.js
  medicines/pars-upload/package.json
  medicines/pars-upload/src/__snapshots__/footer.test.jsx.snap
  medicines/pars-upload/src/footer.test.jsx
  medicines/pars-upload/src/header.js
  medicines/pars-upload/src/pages/_document.js
  medicines/pars-upload/src/setupTests.js
  medicines/pars-upload/yarn.lock
Labels: Automated Tests :robot:, EPIC - PARs process

#768 Pars upload spike
  .github/workflows/pars-upload-branch.yaml
  medicines/doc-index-updater/Cargo.lock
  medicines/doc-index-updater/Cargo.toml
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/create_manager/models.rs
  medicines/doc-index-updater/src/lib.rs
  medicines/doc-index-updater/src/main.rs
  medicines/doc-index-updater/src/pars_upload.rs
  medicines/pars-upload/.babelrc
  medicines/pars-upload/.gitignore
  medicines/pars-upload/.node-version
  medicines/pars-upload/.pa11yci
  medicines/pars-upload/.prettierrc.json
  medicines/pars-upload/README.md
  medicines/pars-upload/cypress.json
  medicines/pars-upload/cypress/integration/tests.js
  medicines/pars-upload/cypress/plugins/index.js
  medicines/pars-upload/cypress/support/commands.js
  medicines/pars-upload/cypress/support/index.js
  medicines/pars-upload/docs/assets/filled-form.png
  medicines/pars-upload/docs/assets/success-message.png
  medicines/pars-upload/docs/example.md
  medicines/pars-upload/jest.config.js
  medicines/pars-upload/next.config.js
  medicines/pars-upload/package.json
  medicines/pars-upload/src/__snapshots__/footer.test.jsx.snap
  medicines/pars-upload/src/button.js
  medicines/pars-upload/src/footer.js
  medicines/pars-upload/src/footer.test.jsx
  medicines/pars-upload/src/header.js
  medicines/pars-upload/src/mhra_logo.js
  medicines/pars-upload/src/pages/_app.js
  medicines/pars-upload/src/pages/_document.js
  medicines/pars-upload/src/pages/index.js
  medicines/pars-upload/src/pages/new-par.js
  medicines/pars-upload/src/setupTests.js
  medicines/pars-upload/src/typography.js
  medicines/pars-upload/src/wizard.js
  medicines/pars-upload/yarn.lock
  medicines/rustfmt.toml
Labels: EPIC - PARs process

#779 Update Rust stable in Docker builds
  hello-world/Dockerfile
  medicines/api/Dockerfile
  medicines/doc-index-updater/Dockerfile
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/service_bus_client/mod.rs
  medicines/doc-index-updater/tests/create_manager.rs
  medicines/doc-index-updater/tests/delete_manager.rs
Labels: r4r :eyes:

#781 Remove curl from docker build for api
  medicines/api/Dockerfile
Labels: security

#783 Bump react-schemaorg to v1.0.2
  medicines/web/package.json
  medicines/web/yarn.lock
Labels: Website 💻

#795 Temporary Blob Storage
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/create_manager/sftp_client.rs
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/pars_upload.rs
  medicines/doc-index-updater/src/storage_client/azure_blob_client.rs
  medicines/doc-index-updater/src/storage_client/client.rs
  medicines/doc-index-updater/src/storage_client/delete.rs
  medicines/doc-index-updater/src/storage_client/get.rs
  medicines/doc-index-updater/src/storage_client/mod.rs
  medicines/doc-index-updater/src/storage_client/models.rs
Labels: EPIC - Auto Batch Process :oncoming_automobile:, EPIC - PARs process

#817 add everything as code to priniciples
  docs/principles/README.md
  docs/principles/everything-as-code.md
  docs/principles/security.md
  docs/words.txt
Labels: r4r :eyes:

#835 use cypress mocks
  .github/workflows/pars-upload-branch.yaml
  .github/workflows/pars-upload-master.yaml
  medicines/pars-upload/Makefile
  medicines/pars-upload/cypress/fixtures/mock_submission_success.json
  medicines/pars-upload/cypress/integration/tests.js
  medicines/pars-upload/doc-index-updater-mocks/HEAD.mock
  medicines/pars-upload/doc-index-updater-mocks/pars/OPTIONS.mock
  medicines/pars-upload/doc-index-updater-mocks/pars/POST.mock
  medicines/pars-upload/package.json
  medicines/pars-upload/src/pages/new-par.js
  medicines/pars-upload/yarn.lock
Labels: EPIC - PARs process

#820 Restrict access to Redis cache to cluster
  infrastructure/environments/non-prod/main.tf
  infrastructure/environments/prod/main.tf
  infrastructure/modules/cluster/main.tf
  infrastructure/modules/cluster/outputs.tf
  infrastructure/modules/service-bus/main.tf
  infrastructure/modules/service-bus/variables.tf
Labels: r4r :eyes:, security

#843 Temporarily fix auth not working in dev env
  medicines/pars-upload/src/auth/authPopup.js
  medicines/pars-upload/src/auth/signInRequest.js
  medicines/pars-upload/src/pages/_app.js
  medicines/pars-upload/src/pages/new-par.js
Labels: EPIC - PARs process

#837 Add tag to pull command
  medicines/api/Makefile
Labels: Tech Infrastructure

#856 Fix name for snapshot container
  infrastructure/modules/logs/main.tf
Labels: BUG :bug:

#848 Add ability to remove products and substances
  medicines/pars-upload/cypress/integration/tests.js
  medicines/pars-upload/src/button.js
  medicines/pars-upload/src/delete_icon.js
  medicines/pars-upload/src/delete_icon.module.css
  medicines/pars-upload/src/field.js
  medicines/pars-upload/src/pages/new-par.js
  medicines/pars-upload/src/products_form.js
  medicines/pars-upload/src/useIncrementingIds.js
  medicines/pars-upload/src/wizard.js
Labels: EPIC - PARs process

#869 Always uppercase product title
  medicines/pars-upload/cypress/integration/tests.js
  medicines/pars-upload/src/products_form.js
Labels: EPIC - PARs process

#868 Fix typo: "License" -> "Licence"
  medicines/doc-index-updater/src/create_manager/models.rs
  medicines/doc-index-updater/src/pars_upload.rs
  medicines/doc-index-updater/src/storage_client/azure_blob_client.rs
  medicines/doc-index-updater/src/storage_client/client.rs
  medicines/pars-upload/cypress/integration/tests.js
  medicines/pars-upload/src/products_form.js
  medicines/pars-upload/src/review_submission.js
Labels: EPIC - PARs process

#863 Fix second submission of the form errorring
  medicines/pars-upload/src/review_submission.js
Labels: BUG :bug:, EPIC - PARs process

#840 Timlee/add pars logging
  .github/workflows/transaction-log-file-creator-ci.yaml
  .github/workflows/transaction-log-file-creator-execution.yaml
  infrastructure/modules/keyvault/main.tf
  infrastructure/modules/logs/main.tf
  medicines/doc-index-updater/README.md
  medicines/doc-index-updater/src/audit_logger/mod.rs
  medicines/doc-index-updater/src/create_manager/mod.rs
  medicines/doc-index-updater/src/delete_manager/mod.rs
  medicines/doc-index-updater/src/document_manager/mod.rs
  medicines/doc-index-updater/src/lib.rs
  medicines/doc-index-updater/src/models.rs
  medicines/doc-index-updater/src/pars_upload.rs
  medicines/doc-index-updater/src/storage_client/azure_blob_client.rs
  medicines/doc-index-updater/src/storage_client/client.rs
  medicines/doc-index-updater/src/storage_client/models.rs
  medicines/doc-index-updater/src/storage_client/sftp_client.rs
  medicines/doc-index-updater/tests/support/mod.rs
  medicines/transaction-log-file-creator/.env.example
  medicines/transaction-log-file-creator/Cargo.lock
  medicines/transaction-log-file-creator/Cargo.toml
  medicines/transaction-log-file-creator/Makefile
  medicines/transaction-log-file-creator/README.md
  medicines/transaction-log-file-creator/src/main.rs
Labels: r4r :eyes:

#870 Capitalise PARs upload field values
  medicines/doc-index-updater/src/lib.rs
  medicines/doc-index-updater/src/multipart_form_data.rs
  medicines/doc-index-updater/src/pars_upload.rs
Labels: EPIC - PARs process

#867 Add logs namespace
  infrastructure/environments/dev/main.tf
  infrastructure/environments/non-prod/main.tf
  infrastructure/environments/prod/main.tf
  infrastructure/modules/cpd/variables.tf
  infrastructure/modules/logs/main.tf
  infrastructure/modules/logs/variables.tf
Labels: r4r :eyes:
