Repository MHRA/products, pull requests merged in 2020-07, with the labels that each got.

#913 Add footnotes as list so they can be styled better
  learning/import/learning_importer.py
  learning/import/test_learning_importer.py
  learning/web/content/modules/antipsychotics/CON155606_12.mdx
  learning/web/content/modules/antipsychotics/CON155606_31.mdx
  learning/web/content/modules/benzodiazepines/CON234573_10.mdx
  learning/web/content/modules/benzodiazepines/CON234573_13.mdx
  learning/web/content/modules/benzodiazepines/CON234573_2.mdx
  learning/web/content/modules/benzodiazepines/CON234573_6.mdx
  learning/web/content/modules/opioids/CON143740_17.mdx
  learning/web/content/modules/ssri/CON146583_21.mdx
  learning/web/content/modules/ssri/CON146583_3.mdx
  learning/web/src/components/Expander/index.js
  learning/web/src/components/Layout/index.js
Labels: r4r :eyes:

#915 Add diagnostic logging to service bus
  infrastructure/environments/dev/main.tf
  infrastructure/environments/non-prod/main.tf
  infrastructure/environments/prod/main.tf
  infrastructure/modules/service-bus/diagnostics.tf
  infrastructure/modules/service-bus/variables.tf
Labels: r4r :eyes:, security

#916 Rename workflow env to correct name
  .github/workflows/transaction-log-file-creator-execution.yaml
Labels: r4r :eyes:

#929 Update .test.mhra urls to .non-prod.mhra
  .github/workflows/medicines-web-master.yaml
  .github/workflows/pars-upload-master.yaml
  medicines/doc-index-updater/scripts/api.scala
Labels: r4r :eyes:

#933 Darkened the border around the searchbar
  medicines/web/src/components/search-wrapper/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/search/index.tsx
Labels: Accessibility :wheelchair:, r4r :eyes:

#937 Timlee/update pa11y config
  .github/workflows/medicines-web-branch.yaml
  .github/workflows/medicines-web-master.yaml
  .github/workflows/medicines-web-release.yaml
  medicines/web/.pa11yci
  medicines/web/pa11y-screenshots/.gitignore
Labels: Accessibility :wheelchair:

#930 Make filter checkbox style darker for accessibility best practice
  medicines/web/src/components/disclaimer/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/disclaimer/index.tsx
  medicines/web/src/components/form-elements/index.tsx
  medicines/web/src/components/search-filter/index.tsx
Labels: Accessibility :wheelchair:, r4r :eyes:

#931 Change search box background to accessible colour
  medicines/web/src/components/search-wrapper/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/search-wrapper/index.tsx
  medicines/web/src/styles/colors.ts
Labels: Accessibility :wheelchair:, r4r :eyes:

#934 Use semantic header hierarchy
  medicines/web/src/components/drug-index/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/drug-index/index.test.tsx
  medicines/web/src/components/drug-index/index.tsx
  medicines/web/src/components/search-filter/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/search-filter/index.test.tsx
  medicines/web/src/components/search-filter/index.tsx
  medicines/web/src/components/search-results/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/search-results/index.test.tsx
  medicines/web/src/components/search-results/index.tsx
Labels: Accessibility :wheelchair:, r4r :eyes:

#939 Spriceware/checkbox submit
  medicines/web/cypress/integration/tests.js
  medicines/web/src/components/form-elements/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/form-elements/index.test.tsx
  medicines/web/src/components/form-elements/index.tsx
  medicines/web/src/components/search-filter/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/search-filter/index.test.tsx
  medicines/web/src/components/search-filter/index.tsx
  medicines/web/src/components/search-results/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/search-results/index.test.tsx
  medicines/web/src/components/search-results/index.tsx
  medicines/web/src/components/search-wrapper/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/search/__snapshots__/index.test.tsx.snap
  medicines/web/src/components/search/index.tsx
  medicines/web/src/model/rerouteType.ts
  medicines/web/src/pages/product/index.tsx
  medicines/web/src/pages/search/index.tsx
Labels: Accessibility :wheelchair:
